use Test::More tests => 15;

use Data::Dumper;
use lib '../../my';
use lib '../lib';

use_ok "pages";
use_ok "utils";
use_ok "validation";
use validation;

mkdir "tmp/t";
$tmp = "tmp/t/\$.x";

utils::write($tmp, "<input type='password'><!-- \$x -->");	# комментарии и символы
$t = template::new($tmp);
is($t, "('<input type=\\\'password\\\'>')");

utils::write($tmp, "<input class=f name=t>");	# input
$t = template::new($tmp);
is($t, "('<input class=f name=t value=\"', utils::escapeHTML(\$x->{'t'}), '\">')");

utils::write($tmp, "<textarea name=t></textarea>");	# textarea
$t = template::new($tmp);
is($t, "('<textarea name=t>', utils::escapeHTML(\$x->{'t'}), '</textarea>')");

utils::write($tmp, "<select class=f name=t><option value=\"\">abc xyz</select>");	# select
$t = template::new($tmp);
is($t, "('<select class=f name=t><option value=\"\">abc xyz', map({'<option value=\"'.utils::escapeHTML(\$_->[0]).'\"'.(\$_->[2]? ' selected': '').'>'.utils::escapeHTML(\$_->[1])} \@{\$x->{'t'}}), '</select>')");

utils::write($tmp, ' $abc.f1 $%{abc}x m${m.u.f}y ');	# переменные
$t = template::new($tmp);
is($t, "(' ', utils::escapeHTML(\$x->{'abc'}{'f1'}), ' ', \$x->{'abc'}, 'x m', utils::escapeHTML(\$x->{'m'}{'u'}{'f'}), 'y ')");

utils::write($tmp, "<textarea name=t></textarea>");	# включения
$t = template::new($tmp);
is($t, "('<textarea name=t>', utils::escapeHTML(\$x->{'t'}), '</textarea>')");

utils::write($tmp, "<for i=x> \$i <br> </for>");	# for
$t = template::new($tmp);
is($t, "(map({ \$x->{'i'} = \$_; (' ', utils::escapeHTML(\$x->{'i'}), ' <br> ') } \@{\$x->{'x'}}))");

utils::write($tmp, "<if a>...</if>");	# if
$t = template::new($tmp);
is($t, "((\$x->{'a'}? '...': ''))");


utils::write($tmp, "<if a>...<else>xyz</if>");	# if
$t = template::new($tmp);
is($t, "((\$x->{'a'}? '...': 'xyz'))");

utils::write($tmp, "<if a>...<elseif b>abc</if>");	# if
$t = template::new($tmp);
is($t, "((\$x->{'a'}? '...': \$x->{'b'}? 'abc': ''))");



#utils::write($tmp, "<script>\nx=y\n</script>");	# coffee
#$t = template::new($tmp);
#is($t, "('<script>
#// Generated by CoffeeScript 1.4.0
#(function() {
#  var x;
#
#  x = y;
#
#}).call(this);
#</script>')");

utils::write($tmp, '$i$j');	# скобки
$t = template::new($tmp);
is($t, "(utils::escapeHTML(\$x->{'i'}), utils::escapeHTML(\$x->{'j'}))");



$request::param = {"email"=>"darviarush\@ya.ru"};
valid "email"=>"email";
is($email, "darviarush\@ya.ru");

#unlink $tmp;


